### model
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
cache_dir: /scratch365/tma2/.cache/
trust_remote_code: true

### accelerator 
flash_attn: fa2
# use_unsloth: true

### method
stage: sft
do_train: true
do_predict: true
finetuning_type: lora
lora_rank: 8
lora_target: all
# deepspeed: configs/deepspeed/ds_z0_config.json

### dataset
dataset: gsm8k_train
dataset_dir: ./data
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: outputs/llama-3.2-3b/gsm8k/sft/lora/train
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb
run_name: llama-3.2-3b_gsm8k_lora_sft

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
save_total_limit: 3
load_best_model_at_end: true
metric_for_best_model: loss
greater_is_better: false

### eval
eval_dataset: gsm8k_eval
per_device_eval_batch_size: 12
eval_strategy: steps
eval_steps: 500
# compute_accuracy: true
predict_with_generate: true


