## model 
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
adapter_name_or_path: outputs/llama-3.2-3b/gsm8k/sft/lora/train
cache_dir: /scratch365/tma2/.cache/
trust_remote_code: true
template: llama3


### export 
export_dir: models/llama-3.2-3b-gsm8k-lora
export_size: 2
export_device: auto
export_legacy_format: false


### huggingface
export_hub_model_id: mtybilly/llama-3.2-3b-gsm8k-lora
