# Experiment
run_name: gsm8k_masked_sft

# Model
model_name_or_path: meta-llama/Llama-3.2-1B
template: llama3_bt
stage: sft
finetuning_type: lora
fp16: false
bf16: true

# Backtrack Training
train_backtrack: true
backtrack_token: "<|BACKTRACK|>"

# Logging
report_to: wandb
wandb_project: Halluc

# Dataset
dataset: gsm8k_masked_train
eval_dataset: gsm8k_masked_eval
converter: sft

# Training
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
save_steps: 100
eval_steps: 100
logging_steps: 10

# Special Tokens
init_special_tokens: true

# Constants
seed: 42
deepspeed: configs/deepspeed/ds_z0_config.json
early_stopping: true

# Evaluation
model: hf-bt
tasks: gsm8k_simple
eval_mode: cli
