# model_name_or_path: null
# adapter_name_or_path: null
# template: null
# export_dir: null
# export_hub_model_id: null

# cache_dir: /scratch365/tma2/.cache/
trust_remote_code: true
export_size: 2
export_device: auto
export_legacy_format: false

### Special Tokens
add_special_tokens: "<|BACKTRACK|>"
new_special_tokens_config: ./configs/llamafactory/token.yaml
