# model_name_or_path: null
# adapter_name_or_path: null
# template: null
# export_dir: null
# export_hub_model_id: null

# cache_dir: /scratch365/tma2/.cache/
trust_remote_code: true
export_size: 2
export_device: auto
export_legacy_format: false

### Special Tokens
new_special_tokens_config: ./configs/llamafactory/token.yaml
force_init_embeddings: true 
# Set force_init_embeddings to true to allow model size to match the tokenizer size.
# It is fine in export mode, as the trained model is loaded after we resize the embeddings.